FROM dokken/ubuntu-20.04
RUN apt-get update
RUN apt-get install -y python3-pip
RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install matplotlib
RUN pip3 install seaborn
RUN pip3 install torch

RUN apt-get install -y git
RUN pip3 install gym==0.21
RUN pip3 install pyglet 
RUN pip3 install networkx
